package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        script {
            scriptContent = "dir /w"
        }
        script {
            scriptContent = """
                echo 1
                echo 2
                echo 3
            """.trimIndent()
        }
    }
    steps {
        insert(2) {
            script {
                name = "step 3"
                scriptContent = "dir /w /w"
            }
        }
    }
}
